name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-job
    - name: Lint Addon
      run: pnpm lint
      working-directory: addon
    - name: Lint Test App
      run: pnpm lint
      working-directory: test-app
    - name: Lint Docs
      run: pnpm lint
      working-directory: docs

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-job
      - name: Run Tests
        run: pnpm test:ember
        working-directory: test-app

  docs:
    name: "Docs App"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-job
      - name: Run Tests
        run: pnpm test:ember
        working-directory: docs

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: |
          rm pnpm-lock.yaml
          pnpm install
      - name: Run Tests
        run: pnpm test:ember
        working-directory: test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: test

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-job
      - name: Run Tests
        run: pnpm ember try:one ${{ matrix.try-scenario }}
        working-directory: test-app
